[project]
name = "control"
version = "0.1.0"
description = "Modern control program on ESP32 for Lesson 'Manufacturing Engineering Experience'"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["micropython-esp32-stubs>=1.26.0.post1"]
